Granting necessary priviledges for CSI-services
SUSE/rook pull request #6
Opened 2019-07-16 14:57 UTC by shaas

- Connected all CSI-relevant service accounts to our PodSecurityPolicy
- Added the correct Flexvolume directory which is still necessary for the rook-agent

2019-07-16 15:33 UTC, denisok approved these changes

2019-07-17 08:04 UTC, denisok commented
@BlaineEXE could you please approve and land it?

2019-07-17 13:38 UTC, shaas commented
Needed to another security related privileges. We need to straighten out that these files are just for testing purposes and should not be used in a productive environment!

2019-07-17 15:30 UTC, BlaineEXE requested changes
Should this PR be against `suse-master`?

For the latest Rook master, there should be a rook-ceph-cmd-reporter RoleBinding as well.
See: https://github.com/rook/rook/pull/3230

2019-07-18 12:33 UTC, shaas commented
> Should this PR be against `suse-master`?
No, only for our suse-master. Changed that. I am wondering why I was master instead of suse-master...
> 
> For the latest Rook master, there should be a rook-ceph-cmd-reporter RoleBinding as well.
> See: [rook#3230](https://github.com/rook/rook/pull/3230)

I was not aware of that PR. Nevertheless, for CSI there are additional privileges needed (e.g. allowedCapabilities).
I suggest to create a psp-csi.yaml which could be used in case of CSI.
@BlaineEXE What do you think?

2019-07-18 16:06 UTC, BlaineEXE commented
I am able to run integration tests (which use CSI) on my dev cluster with the PSP in rook#3230

2019-07-23 12:05 UTC, closed without merging